/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WINDOWS 10
 */
public class apk extends javax.swing.JFrame {
    /**
     * Creates new form app
     */
    public apk() {
        initComponents();
        reset();
    }
    
    void reset(){
        tSUHUASAL.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pSUHUASAL = new javax.swing.JPanel();
        tSUHUASAL = new javax.swing.JTextField();
        tSEKALAASAL = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        tSEKALATUJUAN = new javax.swing.JComboBox<>();
        bKONVERSI = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        vHASIL = new javax.swing.JLabel();
        bRESET = new javax.swing.JButton();
        bCLOSE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("KONVERSI SUHU");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pSUHUASAL.setBorder(javax.swing.BorderFactory.createTitledBorder("SUHU ASAL"));
        pSUHUASAL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pSUHUASAL.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pSUHUASALAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tSUHUASAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSUHUASALActionPerformed(evt);
            }
        });

        tSEKALAASAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelfin", "Fahrenheit" }));
        tSEKALAASAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSEKALAASALActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSUHUASALLayout = new javax.swing.GroupLayout(pSUHUASAL);
        pSUHUASAL.setLayout(pSUHUASALLayout);
        pSUHUASALLayout.setHorizontalGroup(
            pSUHUASALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tSUHUASAL)
            .addComponent(tSEKALAASAL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pSUHUASALLayout.setVerticalGroup(
            pSUHUASALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSUHUASALLayout.createSequentialGroup()
                .addComponent(tSUHUASAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tSEKALAASAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("KONVERSI KE"));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tSEKALATUJUAN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Kelvin", "Fahrenheit" }));
        tSEKALATUJUAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSEKALATUJUANActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tSEKALATUJUAN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tSEKALATUJUAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bKONVERSI.setText("KONVERSI");
        bKONVERSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKONVERSIActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        vHASIL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        vHASIL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vHASIL.setText("0");
        vHASIL.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                vHASILAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vHASIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vHASIL, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );

        bRESET.setText("RESET");
        bRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRESETActionPerformed(evt);
            }
        });

        bCLOSE.setText("CLOSE");
        bCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCLOSEActionPerformed(evt);
            }
        });

        jLabel2.setText("Created By Sanzx_Daniel");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bRESET, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pSUHUASAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bKONVERSI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pSUHUASAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bKONVERSI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bRESET, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCLOSE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRESETActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bRESETActionPerformed

    private void tSUHUASALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSUHUASALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSUHUASALActionPerformed

    private void bCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCLOSEActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bCLOSEActionPerformed

    private void bKONVERSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKONVERSIActionPerformed
        // TODO add your handling code here:
        double suhuasal = Double.parseDouble(tSUHUASAL.getText());
        String SEKALAASAL = tSEKALAASAL.getSelectedItem().toString();
        String SEKALATUJUAN = tSEKALATUJUAN.getSelectedItem().toString();
        double hasil = 0;
        
        if (SEKALAASAL.equals("Celsius") && SEKALATUJUAN.equals("Celsius")) {
            hasil = suhuasal;
        } else if (SEKALAASAL.equals("Celsius") && SEKALATUJUAN.equals("Kelvin")) {
            hasil = suhuasal + 273.15;
        } else if (SEKALAASAL.equals("Celsius") && SEKALATUJUAN.equals("Fahrenheit")) {
            hasil = suhuasal * 9/5 + 32;
        } else if (SEKALAASAL.equals("Kelvin") && SEKALATUJUAN.equals("Kelvin")) {
            hasil = suhuasal;
        } else if (SEKALAASAL.equals("Kelvin") && SEKALATUJUAN.equals("Celsius")) {
            hasil = suhuasal - 273.15;
        } else if (SEKALAASAL.equals("Kelvin") && SEKALATUJUAN.equals("Fahrenheit")) {
            hasil = suhuasal - 273.15 * 9/5 + 32;
        } else if (SEKALAASAL.equals("Fahrenheit") && SEKALATUJUAN.equals("Fahrenheit")) {
            hasil = suhuasal;
        } else if (SEKALAASAL.equals("Fahrenheit") && SEKALATUJUAN.equals("Celsius")) {
            hasil = suhuasal - 32 * 5/9;
        } else if (SEKALAASAL.equals("Fahrenheit") && SEKALATUJUAN.equals("Kelvin")) {
            hasil = suhuasal - 32 * 5/9 + 273.15;
       
        }
         String SEKALA = SEKALATUJUAN.substring(0, 1);
        vHASIL.setText(String.format("%.2f", hasil) + " \u00B0" + SEKALA);
    }//GEN-LAST:event_bKONVERSIActionPerformed
 
    private void tSEKALAASALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSEKALAASALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSEKALAASALActionPerformed

    private void pSUHUASALAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pSUHUASALAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pSUHUASALAncestorAdded

    private void tSEKALATUJUANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSEKALATUJUANActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tSEKALATUJUANActionPerformed

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void vHASILAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_vHASILAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_vHASILAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCLOSE;
    private javax.swing.JButton bKONVERSI;
    private javax.swing.JButton bRESET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pSUHUASAL;
    private javax.swing.JComboBox<String> tSEKALAASAL;
    private javax.swing.JComboBox<String> tSEKALATUJUAN;
    private javax.swing.JTextField tSUHUASAL;
    private javax.swing.JLabel vHASIL;
    // End of variables declaration//GEN-END:variables
}
