/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasi;

/**
 *
 * @author WINDOWS 10
 */
public class PERSEGI extends javax.swing.JFrame {
double sisi,luas,keliling;
    /**
     * Creates new form PERSEGI
     */
    public PERSEGI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tSISI = new javax.swing.JTextField();
        tHITUNG = new javax.swing.JButton();
        tRESET = new javax.swing.JButton();
        tKEMBALI = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tLUAS = new javax.swing.JTextField();
        tKELILING = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("PERSEGI");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("SISI");

        tSISI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSISIActionPerformed(evt);
            }
        });

        tHITUNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/calculator.png"))); // NOI18N
        tHITUNG.setText("HITUNG");
        tHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHITUNGActionPerformed(evt);
            }
        });

        tRESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/circular.png"))); // NOI18N
        tRESET.setText("RESET");
        tRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRESETActionPerformed(evt);
            }
        });

        tKEMBALI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/return.png"))); // NOI18N
        tKEMBALI.setText("KEMBALI");
        tKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKEMBALIActionPerformed(evt);
            }
        });

        jLabel4.setText("LUAS");

        jLabel5.setText("KELILING");

        tLUAS.setEditable(false);
        tLUAS.setAutoscrolls(false);

        tKELILING.setEditable(false);
        tKELILING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKELILINGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tHITUNG)
                        .addGap(18, 18, 18)
                        .addComponent(tRESET)
                        .addGap(18, 18, 18)
                        .addComponent(tKEMBALI))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tSISI)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tLUAS)
                            .addComponent(tKELILING))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tSISI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHITUNG)
                    .addComponent(tRESET)
                    .addComponent(tKEMBALI))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tLUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tKELILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tSISIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSISIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSISIActionPerformed

    private void tHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHITUNGActionPerformed
        // TODO add your handling code here:
        sisi = Double.parseDouble(tSISI.getText());
        luas = sisi*sisi;
        keliling = 4*sisi;
        tLUAS.setText(String.valueOf(luas));
        tKELILING.setText(String.valueOf(keliling));
    }//GEN-LAST:event_tHITUNGActionPerformed

    private void tRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRESETActionPerformed
        // TODO add your handling code here:
        tSISI.setText("");
        tLUAS.setText("");
        tKELILING.setText("");
    }//GEN-LAST:event_tRESETActionPerformed

    private void tKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKEMBALIActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
    }//GEN-LAST:event_tKEMBALIActionPerformed

    private void tKELILINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKELILINGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKELILINGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERSEGI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton tHITUNG;
    private javax.swing.JTextField tKELILING;
    private javax.swing.JButton tKEMBALI;
    private javax.swing.JTextField tLUAS;
    private javax.swing.JButton tRESET;
    private javax.swing.JTextField tSISI;
    // End of variables declaration//GEN-END:variables
}
